import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import 'bootstrap-icons/font/bootstrap-icons.min.css'
import Navigation from '@/components/navigation'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
